spring.application.name=SmartClinic

# Database Configuration
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=SmartClinic;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123
server.port=8088
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Stripe Configuration (Test Mode)
stripe.api.key=sk_test_51SzHp9AeogsNM4XjdgOka2oOiSvWHWpDO1iLK5ccBPp56wb1debN3EedPscmM4yxuIM2qreBijXiP77JH4FwwRQc00PHIf8zg5

# Email Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=drdilinifonseka@gmail.com
spring.mail.password=ezxc rcay zwyf ewoo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Admin Settings
admin.email=drdilinifonseka@gmail.com
